services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: api
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rest-api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: task_management_system
      SPRINGDOC_SWAGGER_UI_URL: /v1/task-management-api-docs
      SPRINGDOC_API_DOCS_PATH: /v1/task-management-api-docs
      SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES: true
      JWT_ACCESS_PATH: /app/jwt/access.txt
      JWT_REFRESH_PATH: /app/jwt/refresh.txt
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rest-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
